### ISSUE TITLE
Upgrade theme to SFUI 0.7

### ISSUE THREAD

**Issue by patzick** [DivanteLtd/shopware-pwa#595]
## TODO

- [x] replace css variables
- [x] adjust Header
- [x] Add TopBar with SwCurrency
- [x] adjust navbar in categories
- [x] adjust BottomNavigation
- [ ] adjust Category view
- [x] adjust cart sidebar
- [ ] Add possibility to change ProductListing view  -> need to implement in #655 
- [x] adjust Sidebar
- [x] adjust Checkout
- [x] adjust MyAccount
- [x] adjust ErrorPage
- [x] adjust modals (Log In)
- [ ] remove icons in SortBy Select -> need to fix in #656 
- [ ] adjust Colors in Filters  -> this is already taking care of in #647 
- [x] adjust Colors in Product Page
- [x] adjust Product
- [x] Fix banner 

## Acceptance criteria
- [ ] default-theme package is updated to the newest version
- [ ] all components are upgraded according to [migration guide](https://docs.storefrontui.io/migration-guide.html#migration-to-v0-7-0)
- [ ] new designs from pages are applied

**Comment by rmakara** [comment]
To check against new Figma designs:
* [ ] Top Navigation
* [ ] Category Page
* [ ] Product Page
* [ ] Cart
* [ ] Checkout
* [ ] My Account

**Comment by akrajna** [comment]
* the currency sign should be in one line with the price
<img width="539" alt="CurrencyEuro" src="https://user-images.githubusercontent.com/57936972/81035983-8de7a680-8e9d-11ea-9964-cbca21b8999c.png">
* the numbers in the price should be on the same height
<img width="368" alt="PriceNumberHight" src="https://user-images.githubusercontent.com/57936972/81036017-b8d1fa80-8e9d-11ea-9f12-9bc34bde8961.png">
* navbar in categories - it is impossible to enter the category if there are subcategories e.g. it is impossible to enter category Movies-Toys, user can enter only the subcategories: Test-Subactegory-1 and Test-Subactegory-2
![Subcategories](https://user-images.githubusercontent.com/57936972/81036726-6cd48500-8ea0-11ea-9436-64ec72426b85.gif)
* there is no indication that product was added to the cart. There should be circle with numbers of items added to the cart on the cart icon.
<img width="194" alt="basket" src="https://user-images.githubusercontent.com/57936972/81037327-97bfd880-8ea2-11ea-9a58-14c51ad773d3.png">

**Comment by akrajna** [comment]
* navbar in categories - it is impossible to enter category if there is subcategory e.g. it is impossible to enter category Movies&Toys 
![CategoryChange](https://user-images.githubusercontent.com/57936972/81038543-b031f200-8ea6-11ea-9e40-7a4bde09e5e4.gif)
* cart sidebar:
   * in the green circle there should be shown number of total items instead of 'x' closing sign
   * the 'x' closing sign should be in upper right corner
   *  'My cart' and 'Total items should be in bold
   * the name of the product should be in larger font 
   * the quantity field is too big
   * the button at the bottom should be black instead of green
   * it should look as below: 
<img width="224" alt="CartFigma1" src="https://user-images.githubusercontent.com/57936972/81038746-6bf32180-8ea7-11ea-8ec7-49fa22ee6b64.png">
   * it looks as below:
<img width="215" alt="cartPWA1" src="https://user-images.githubusercontent.com/57936972/81038842-aeb4f980-8ea7-11ea-89d9-4b42c5abc5ad.png">

**Comment by akrajna** [comment]
* there are two arrows to sort by price, there should be one arrow
<img width="660" alt="SortByPrice" src="https://user-images.githubusercontent.com/57936972/81039444-554dca00-8ea9-11ea-9b6c-374d3e5d4cfd.png">
* changeing view is not working 

<img width="522" alt="View" src="https://user-images.githubusercontent.com/57936972/81039630-e15ff180-8ea9-11ea-99d6-cbd635d7659b.png">
